name: uniestagios
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  watch: $runner watch --delete-conflicting-outputs
  build: $runner build --delete-conflicting-outputs
  buildApk: flutter build apk --release --target-platform android-arm

dependencies:
  brasil_fields: ^1.4.2
  cloud_firestore: ^3.1.12
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  file_picker: ^4.5.1
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4
  flutter_svg: ^1.0.3
  get: 4.6.1
  get_it: ^7.2.0
  image_gallery_saver: ^1.7.1
  intl: ^0.17.0
  json_serializable: ^6.1.6
  permission_handler: ^9.2.0
  pinput: ^2.2.7
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

fonts:
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Light.ttf
      - asset: fonts/Ubuntu-Bold.ttf
      - asset: fonts/Ubuntu-Italic.ttf
      - asset: fonts/Ubuntu-Medium.ttf
        style: light
