// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEn0yROJ1EVmDa7H-j5V4hLAkvBPWMhpY',
    appId: '1:303238579276:web:ff0c4b57ad45aa45cde0e9',
    messagingSenderId: '303238579276',
    projectId: 'uniestagios-b0f25',
    authDomain: 'uniestagios-b0f25.firebaseapp.com',
    storageBucket: 'uniestagios-b0f25.appspot.com',
    measurementId: 'G-RD0DQ890DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZ28DpZdibr1lkah_dscbGGpy70zOWxY',
    appId: '1:303238579276:android:0c557129e4cd431bcde0e9',
    messagingSenderId: '303238579276',
    projectId: 'uniestagios-b0f25',
    storageBucket: 'uniestagios-b0f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJtUrCrT2BIimzOhC37psjLIVYNZlBUc',
    appId: '1:303238579276:ios:f2981a4303c5979fcde0e9',
    messagingSenderId: '303238579276',
    projectId: 'uniestagios-b0f25',
    storageBucket: 'uniestagios-b0f25.appspot.com',
    iosClientId: '303238579276-9ffkov4cpsvsjv50ogakpfkir210fj3h.apps.googleusercontent.com',
    iosBundleId: 'com.univas.uniestagios',
  );
}
